### ISSUE TITLE
Interact with the Docker daemon from a container

### ISSUE THREAD

**Issue by nirekin** [lagoon-platform/api#1]
Currently the API can't interact with the Docker daemon when the API container is running on the daemon itself.

**Make a POC to validate that this is doable.**

Some go projects like 'Portainer' are doing it, digging in their code should help.

In order to connect the daemon a portainer  service is configured this way:
```yaml
  portainer:
    image: portainer/portainer
    ports:
      - "9000:9000"
    command: -H unix:///var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
```
